version: "3.9"

services:
  app:
    build: 
      target: dev
    container_name: testeDocker-api
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node
      - /home/node/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: testeDocker-db
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=jestprisma
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5